"""initial

Revision ID: a2c48f34322d
Revises: 
Create Date: 2026-02-13 22:49:04.924106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c48f34322d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('category_groups',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('retailers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('affiliate_tag', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('trends',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('stamp_score', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('beauty_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skin_tone', sa.String(length=50), nullable=True),
    sa.Column('undertone', sa.String(length=50), nullable=True),
    sa.Column('skin_type', sa.String(length=50), nullable=True),
    sa.Column('coverage', sa.String(length=50), nullable=True),
    sa.Column('finish', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('builds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builds_user_id'), ['user_id'], unique=False)

    op.create_table('categories',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('group_key', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_key'], ['category_groups.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('trend_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trend_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_articles_trend_id'), ['trend_id'], unique=False)

    op.create_table('trend_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trend_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_videos_trend_id'), ['trend_id'], unique=False)

    op.create_table('user_notification_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trend_notifications', sa.Boolean(), nullable=False),
    sa.Column('price_drop_alerts', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_style_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('style_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_style_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_style_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('category_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.String(length=50), nullable=False),
    sa.Column('filter_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('filter_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_key'], ['categories.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('stamp_score', sa.Integer(), nullable=False),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('amazon_asin', sa.String(length=20), nullable=True),
    sa.Column('open_beauty_facts_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('walmart_item_id', sa.String(length=50), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_key'], ['categories.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_amazon_asin'), ['amazon_asin'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_key'), ['category_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_upc'), ['upc'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_walmart_item_id'), ['walmart_item_id'], unique=False)

    op.create_table('build_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.String(length=36), nullable=False),
    sa.Column('category_key', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_key'], ['categories.key'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('build_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_slots_build_id'), ['build_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_product_id'), ['product_id'], unique=False)

    op.create_table('product_filter_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('filter_key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_filter_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_filter_values_filter_key'), ['filter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_filter_values_product_id'), ['product_id'], unique=False)

    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'source', name='uq_product_price_source')
    )
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_prices_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_prices_source'), ['source'], unique=False)

    op.create_table('product_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_reviews_product_id'), ['product_id'], unique=False)

    op.create_table('trend_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trend_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_products_trend_id'), ['trend_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trend_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_products_trend_id'))

    op.drop_table('trend_products')
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_reviews_product_id'))

    op.drop_table('product_reviews')
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_prices_source'))
        batch_op.drop_index(batch_op.f('ix_product_prices_product_id'))

    op.drop_table('product_prices')
    with op.batch_alter_table('product_filter_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_filter_values_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_filter_values_filter_key'))

    op.drop_table('product_filter_values')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_product_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('build_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_slots_build_id'))

    op.drop_table('build_slots')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_walmart_item_id'))
        batch_op.drop_index(batch_op.f('ix_products_upc'))
        batch_op.drop_index(batch_op.f('ix_products_category_key'))
        batch_op.drop_index(batch_op.f('ix_products_amazon_asin'))

    op.drop_table('products')
    op.drop_table('category_filters')
    with op.batch_alter_table('user_style_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_style_preferences_user_id'))

    op.drop_table('user_style_preferences')
    op.drop_table('user_notification_settings')
    with op.batch_alter_table('trend_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_videos_trend_id'))

    op.drop_table('trend_videos')
    with op.batch_alter_table('trend_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_articles_trend_id'))

    op.drop_table('trend_articles')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))

    op.drop_table('refresh_tokens')
    op.drop_table('categories')
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builds_user_id'))

    op.drop_table('builds')
    op.drop_table('beauty_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('trends')
    op.drop_table('retailers')
    op.drop_table('category_groups')
    op.drop_table('brands')
    # ### end Alembic commands ###
