import base64
import json
import re
from typing import Literal

import anthropic
import httpx
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, field_validator

from app.config import get_settings
from app.middleware.auth_middleware import get_subscribed_user
from app.models.user import User

router = APIRouter(prefix="/analyze", tags=["analyze"])
settings = get_settings()

Verdict = Literal["REAL", "FAKE", "SCAM", "AI_GENERATED", "UNCERTAIN"]
Category = Literal["fact", "link", "media", "general"]

SYSTEM_PROMPT = """You are ShortStamp, an AI legitimacy checker. You analyze screenshots and content to determine whether they are real, fake, scam, AI-generated, or uncertain.

You MUST respond with a valid JSON object in this exact format:
{
  "verdict": "REAL" | "FAKE" | "SCAM" | "AI_GENERATED" | "UNCERTAIN",
  "confidence": <integer 0-100>,
  "explanation": "<1-3 clear sentences explaining your verdict>",
  "category": "fact" | "link" | "media" | "general"
}

Verdict definitions:
- REAL: The content is legitimate, factual, and trustworthy
- FAKE: The content is fabricated, false, or misleading
- SCAM: The content is a scam attempt (phishing, fraud, deceptive marketing)
- AI_GENERATED: The content appears to be AI-generated (images, text, deepfakes)
- UNCERTAIN: Not enough signal to make a determination

Category definitions:
- fact: A claim, statistic, news headline, or factual assertion
- link: A URL, domain, or web link being evaluated
- media: An image, video frame, or visual content
- general: General content or mixed content that doesn't fit the above

Be direct and concise. Your explanation should be 1-3 sentences maximum. Do not hedge excessively — give a clear verdict when the evidence supports it."""

FACTCHECK_PROMPT = """You are ShortStamp, an AI fact-checker. Analyze the provided text for accuracy, bias, and legitimacy.

You MUST respond with a valid JSON object in this exact format:
{
  "verdict": "REAL" | "FAKE" | "SCAM" | "AI_GENERATED" | "UNCERTAIN",
  "confidence": <integer 0-100>,
  "explanation": "<1-3 clear sentences explaining your verdict>",
  "category": "fact" | "link" | "media" | "general"
}

Use REAL if the claims are accurate and unbiased. Use FAKE if claims are false or misleading. Use SCAM if the text is deceptive or a phishing/fraud attempt. Use UNCERTAIN if there is not enough information to verify. Be direct and concise."""

AI_DETECTION_TEXT_PROMPT = """You are ShortStamp, an AI content detector. Analyze whether the provided text was written by a human or generated by AI.

Look for AI writing patterns: unnaturally perfect grammar, repetitive sentence structures, generic hedging phrases, lack of genuine personal voice, suspiciously broad knowledge without specificity, and overly coherent multi-topic coverage.

You MUST respond with a valid JSON object in this exact format:
{
  "verdict": "REAL" | "AI_GENERATED" | "UNCERTAIN",
  "confidence": <integer 0-100>,
  "explanation": "<1-3 clear sentences explaining your verdict>",
  "category": "fact" | "link" | "media" | "general"
}

Use REAL if the text reads as genuinely human-written. Use AI_GENERATED if patterns strongly suggest AI authorship. Use UNCERTAIN if signals are mixed. Category should almost always be "general" or "fact"."""

VIDEO_ANALYSIS_PROMPT = """You are ShortStamp, an AI legitimacy checker for video content. You have been given a transcript of a video. Analyze whether the claims, information, and intent in this video are legitimate.

You MUST respond with a valid JSON object in this exact format:
{
  "verdict": "REAL" | "FAKE" | "SCAM" | "AI_GENERATED" | "UNCERTAIN",
  "confidence": <integer 0-100>,
  "explanation": "<1-3 clear sentences explaining your verdict>",
  "category": "fact" | "link" | "media" | "general"
}

Use REAL if the content is factual and legitimate. Use FAKE if claims are false or misleading. Use SCAM if the video is promoting fraud, phishing, or deceptive schemes. Use AI_GENERATED if the speech/content appears AI-synthesized. Category should be "media" for most video content."""

AI_DETECTION_VIDEO_PROMPT = """You are ShortStamp, an AI video detector. You have been given a transcript of a video. Analyze whether the speech, delivery patterns, and content suggest AI generation (text-to-speech, AI voiceover, AI-scripted content, deepfake narration).

Look for: unnatural phrasing, lack of verbal fillers and hesitations, perfectly structured delivery, generic language, absence of genuine human spontaneity.

You MUST respond with a valid JSON object in this exact format:
{
  "verdict": "REAL" | "AI_GENERATED" | "UNCERTAIN",
  "confidence": <integer 0-100>,
  "explanation": "<1-3 clear sentences explaining your verdict>",
  "category": "media"
}"""


class AnalyzeRequest(BaseModel):
    image_base64: str
    hint: str | None = None

    @field_validator("image_base64")
    @classmethod
    def validate_base64(cls, v: str) -> str:
        if v.startswith("data:"):
            v = re.sub(r"^data:[^;]+;base64,", "", v)
        try:
            base64.b64decode(v, validate=True)
        except Exception:
            raise ValueError("Invalid base64 image data")
        return v


class AnalyzeTextRequest(BaseModel):
    text: str
    mode: Literal["factcheck", "ai_detection"]


class AnalyzeUrlRequest(BaseModel):
    url: str
    mode: Literal["video", "ai_detection"]


class AnalyzeResponse(BaseModel):
    verdict: Verdict
    confidence: int
    explanation: str
    category: Category


def _extract_youtube_id(url: str) -> str | None:
    patterns = [
        r"(?:youtube\.com/watch\?v=|youtu\.be/|youtube\.com/shorts/)([A-Za-z0-9_-]{11})",
    ]
    for pattern in patterns:
        m = re.search(pattern, url)
        if m:
            return m.group(1)
    return None


async def _get_video_transcript(url: str) -> str:
    """Return transcript text for a video URL, or raise HTTPException."""
    video_id = _extract_youtube_id(url)
    if video_id:
        try:
            from youtube_transcript_api import YouTubeTranscriptApi, NoTranscriptFound, TranscriptsDisabled
            transcript_list = await __import__("asyncio").get_event_loop().run_in_executor(
                None,
                lambda: YouTubeTranscriptApi.get_transcript(video_id, languages=["en", "en-US"]),
            )
            return " ".join(entry["text"] for entry in transcript_list)
        except (NoTranscriptFound, TranscriptsDisabled):
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="No English transcript available for this video.",
            )
        except Exception as e:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"Could not fetch transcript: {e}",
            )

    # Non-YouTube URL: try fetching page text as a fallback
    try:
        async with httpx.AsyncClient(timeout=10.0, follow_redirects=True) as client:
            resp = await client.get(url, headers={"User-Agent": "Mozilla/5.0"})
            resp.raise_for_status()
            # Strip HTML tags for a rough text extraction
            text = re.sub(r"<[^>]+>", " ", resp.text)
            text = re.sub(r"\s+", " ", text).strip()
            if len(text) < 100:
                raise ValueError("Too little text")
            return text[:8000]
    except Exception:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Could not fetch content from this URL. YouTube links and public web pages are supported.",
        )


def _parse_claude_response(response_text: str) -> AnalyzeResponse:
    json_match = re.search(r"\{.*\}", response_text, re.DOTALL)
    if not json_match:
        raise ValueError("No JSON in response")
    data = json.loads(json_match.group())
    confidence = max(0, min(100, int(data.get("confidence", 50))))
    verdict = data.get("verdict", "UNCERTAIN")
    if verdict not in ("REAL", "FAKE", "SCAM", "AI_GENERATED", "UNCERTAIN"):
        verdict = "UNCERTAIN"
    category = data.get("category", "general")
    if category not in ("fact", "link", "media", "general"):
        category = "general"
    return AnalyzeResponse(
        verdict=verdict,
        confidence=confidence,
        explanation=data.get("explanation", "Unable to determine legitimacy."),
        category=category,
    )


async def _call_claude(system: str, user_text: str, settings) -> AnalyzeResponse:
    client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
    try:
        message = await client.messages.create(
            model="claude-3-5-sonnet-20241022",
            max_tokens=512,
            system=system,
            messages=[{"role": "user", "content": user_text}],
        )
        return _parse_claude_response(message.content[0].text.strip())
    except anthropic.APIError as e:
        raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail=f"AI service error: {e}")
    except (ValueError, KeyError, TypeError) as e:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"Failed to parse AI response: {e}")


def _demo_response(verdicts: list[Verdict] | None = None) -> AnalyzeResponse:
    import random
    all_verdicts: list[Verdict] = verdicts or ["REAL", "FAKE", "SCAM", "AI_GENERATED", "UNCERTAIN"]
    categories: list[Category] = ["fact", "link", "media", "general"]
    verdict = random.choice(all_verdicts)
    explanations: dict[str, str] = {
        "REAL": "This content appears legitimate. The sources and claims are consistent with verified information.",
        "FAKE": "This content shows signs of being fabricated. Key details do not match known verified sources.",
        "SCAM": "This appears to be a scam attempt. The domain or content displays classic phishing patterns.",
        "AI_GENERATED": "This content shows strong indicators of AI generation. Patterns are consistent with generative models.",
        "UNCERTAIN": "Not enough signal to make a clear determination. Treat with caution.",
    }
    return AnalyzeResponse(
        verdict=verdict,
        confidence=random.randint(65, 95),
        explanation=explanations[verdict],
        category=random.choice(categories),
    )


@router.post("", response_model=AnalyzeResponse)
async def analyze(
    body: AnalyzeRequest,
    current_user: User = Depends(get_subscribed_user),
):
    """Analyze a screenshot for legitimacy."""
    if settings.anthropic_api_key in (None, "", "demo"):
        return _demo_response()

    if not settings.anthropic_api_key:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="AI service not configured")

    client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
    user_content: list = [
        {"type": "image", "source": {"type": "base64", "media_type": "image/png", "data": body.image_base64}},
        {"type": "text", "text": (
            f"User hint: {body.hint}\n\nAnalyze the screenshot above for legitimacy. Respond with JSON only."
            if body.hint else
            "Analyze the screenshot above for legitimacy. Respond with JSON only."
        )},
    ]
    try:
        message = await client.messages.create(
            model="claude-3-5-sonnet-20241022",
            max_tokens=512,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_content}],
        )
        return _parse_claude_response(message.content[0].text.strip())
    except anthropic.APIError as e:
        raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail=f"AI service error: {e}")
    except (ValueError, KeyError, TypeError) as e:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"Failed to parse AI response: {e}")


@router.post("-text", response_model=AnalyzeResponse)
async def analyze_text(
    body: AnalyzeTextRequest,
    current_user: User = Depends(get_subscribed_user),
):
    """Fact-check or AI-detect plain text."""
    if not body.text.strip():
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="Text cannot be empty.")

    if settings.anthropic_api_key in (None, "", "demo"):
        verdicts: list[Verdict] = ["REAL", "AI_GENERATED", "UNCERTAIN"] if body.mode == "ai_detection" else None
        return _demo_response(verdicts)

    system = FACTCHECK_PROMPT if body.mode == "factcheck" else AI_DETECTION_TEXT_PROMPT
    user_text = f"Analyze this text:\n\n{body.text[:8000]}\n\nRespond with JSON only."
    return await _call_claude(system, user_text, settings)


@router.post("-url", response_model=AnalyzeResponse)
async def analyze_url(
    body: AnalyzeUrlRequest,
    current_user: User = Depends(get_subscribed_user),
):
    """Analyze a video or web URL — fetches transcript/content then runs AI analysis."""
    transcript = await _get_video_transcript(body.url)

    if settings.anthropic_api_key in (None, "", "demo"):
        verdicts: list[Verdict] = ["REAL", "AI_GENERATED", "UNCERTAIN"] if body.mode == "ai_detection" else None
        return _demo_response(verdicts)

    system = AI_DETECTION_VIDEO_PROMPT if body.mode == "ai_detection" else VIDEO_ANALYSIS_PROMPT
    user_text = f"Video URL: {body.url}\n\nTranscript:\n{transcript[:8000]}\n\nRespond with JSON only."
    return await _call_claude(system, user_text, settings)
